version: "3"
services:
  test:
    build: .
    links:
      - web
      - redis
  web:
    build: ../cartoongrabber-web
    links:
      - redis
    ports:
      - "8081:8081"
  redis:
    image: redis
    ports:
      - "6379:6379"